# Generated by Django 3.1.4 on 2021-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Fecha',
            new_name='Fecha_Nacimiento',
        ),
        migrations.AlterField(
            model_name='carros',
            name='Imagen',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='Imagen',
            field=models.URLField(max_length=600),
        ),
    ]
